# Generated by Django 5.2 on 2025-04-22 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=500)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('reservation_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
