# Generated by Django 5.2 on 2025-04-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='service',
            field=models.CharField(choices=[('option1', 'Haircuts & Styling'), ('option2', 'Hair Treatment & Repair'), ('option3', 'Spa & Relaxation Therapies'), ('option4', 'Nails & Manicure'), ('option5', 'Pedicure & Foot Spa')], default='option1', max_length=100),
        ),
    ]
