# Generated by Django 5.2 on 2025-04-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_contact_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
